language: node_js
node_js:
 - "node"

cache:
 npm: true # this cashes ~/.npm folder on Travis
 directories:
  # we also need to cache folder with Cypress binary
  - ~/.cache
install:
 - npm ci

script:
 - npm run start:dev &
 - npm run lint
 - $(npm bin)/cypress run --record  --key 6e551b3c-9d2f-48e8-9980-dd7ae1950161
